# Generated by Django 4.1.13 on 2023-11-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_comment_postlike_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
