# Generated by Django 4.1.13 on 2023-12-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
